# Check https://circleci.com/docs/2.0/language-java/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn verify
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
              - develop
              - release/*
              - bugfix/*
              - feature/*
      - test:
        requires:
          - build
        filters:
          branches:
            only:
              - master
              - develop
              - release/*
              - bugfix/*
              - feature/*